# Assignment day 3

In [1]:
import numpy as np

arr1 = np.arange(2,51)

print(arr1[0:50:3])

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


In [12]:
import numpy as np

lis = []
lis1 = []

while len(lis) < 5:
    n = raw_input()
    n1 = n.split(" ")
    lis.append(n1)
    
while len(lis1) < 5:
    a = raw_input()
    b = a.split(" ")
    lis1.append(b)
    
    
lis.sort()
lis1.sort()
print(lis)
print(lis1)
arr = np.array(lis)
arr1 = np.array(lis1)
arr2 = np.concatenate([arr,arr1])

print(''.join(map(str,arr2)))

23r
433
t45
23
1
f34t
5y
34t
56u
t3
[['1'], ['23'], ['23r'], ['433'], ['t45']]
[['34t'], ['56u'], ['5y'], ['f34t'], ['t3']]
['1']['23']['23r']['433']['t45']['34t']['56u']['5y']['f34t']['t3']


In [21]:
import numpy as np

a = np.array([[11 ,12,13,11], [21, 22, 23, 24], [31,32,33,34]])

print(a.shape)
print(a.ndim)

(3L, 4L)
2


In [44]:
import numpy as np

a = np.array([1,2,3,4,5,6])
b = np.reshape(a, (-1, 2))
print(A)
print("\n")
print(B)

[1 2 3 4 5 6]


[[1 2]
 [3 4]
 [5 6]]


In [45]:
x = x = np.array([1, 2])
y = np.expand_dims(x, axis=1)

print(x)
print("\n")
print(y)

[1 2]


[[1]
 [2]]


In [51]:
import numpy as np

a = np.arange(10)
print(a.shape)
b = a[:, np.newaxis].shape
print(b)

(10L,)
(10L, 1L)


In [53]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

a1 = np.array([[1, 1], [2, 2]])
a2 = np.array([[3, 3],[4, 4]])

ver = np.vstack((a1, a2))
hor= np.hstack((a1, a2))
print(ver)
print("\n")
print(hor)

[[1 1]
 [2 2]
 [3 3]
 [4 4]]


[[1 1 3 3]
 [2 2 4 4]]


In [56]:
import numpy as np 
  
def unique(list1): 
    x = np.array(list1) 
    print(np.unique(x)) 
    
list1 = [10, 20, 10, 30, 40, 40]        
unique(list1) 

[10 20 30 40]
